# AIR QUALITY PRO V2 - SENSOR INTEGRATION MODULE
# ============================================================================
# ESP32-S3 Display (UEAIDISP 5" 800×480) Air Quality Detector
# VERSION 2: Advanced Multi-Gas + Particulate Matter Detection
# 
# Sensors:
#   - SCD41: CO₂ (I2C)
#   - BME680: VOC/IAQ + Environmental (I2C)
#   - SPS30: Particulate Matter (PM1.0/2.5/4/10) (I2C)
#   - ZE07-CO: Dedicated CO sensor (UART)
# ============================================================================

# NOTE: This module assumes:
# - Main I2C bus: GPIO8 (SDA), GPIO9 (SCL) @ 100kHz
# - ZE07-CO UART: GPIO17 (TX), GPIO18 (RX) on UART1
# - Adjust pin assignments if your wiring differs

globals:
  # ========== ADVANCED CALIBRATION SYSTEM ==========
  - id: g_baseline_valid
    type: bool
    restore_value: true
    initial_value: "false"
    # SCD41 is auto-calibrating, but track calibration status
    
  - id: g_calibration_timestamp
    type: uint32_t
    restore_value: true
    initial_value: "0"
    
  - id: g_calibration_count
    type: int
    restore_value: true
    initial_value: "0"

  # ========== AIR QUALITY ALERT STATE ==========
  - id: aq_alert_level
    type: int
    restore_value: no
    initial_value: "0"
    # 0=Normal, 1=Warning, 2=Alert, 3=Critical
    
  - id: aq_alert_gas
    type: std::string
    restore_value: no
    initial_value: '""'
    # Which gas triggered the alert

  # ========== PM2.5 EXPOSURE TRACKING ==========
  - id: pm25_exposure_minutes
    type: uint32_t
    restore_value: no
    initial_value: "0"
    # Cumulative exposure to PM2.5 > WHO guideline (15µg/m³)

uart:
  # ========== ZE07-CO DEDICATED SENSOR (UART1) ==========
  - id: uart_ze07_co
    tx_pin: GPIO17
    rx_pin: GPIO18
    baud_rate: 9600
    stop_bits: 1
    parity: NONE
    debug:
      direction: BOTH
      dummy_receiver_enabled: false

i2c:
  # ========== MAIN I2C BUS (SCD41, BME680, SPS30) ==========
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    frequency: 100kHz
    scan: true

# ============================================================================
# SENSOR DEFINITIONS
# ============================================================================

sensor:
  # ===== ZE07-CO DEDICATED CO SENSOR (UART) =====
  # Advantages over MiCS:
  #   - True amperometric sensor (more stable baseline)
  #   - No calibration needed (factory calibrated)
  #   - 0-1000 ppm range (better than MiCS)
  #   - Industrial-grade accuracy (±5% or ±10ppm)
  #   - Minimal drift over time
  
  - platform: modbus_controller
    modbus_controller_id: modbus_ze07
    id: ze07_co_raw
    name: "ZE07-CO Raw"
    register_type: holding
    address: 0x0000
    unit_of_measurement: "ppm"
    value_type: U_WORD
    accuracy_decimals: 1
    update_interval: 5s
    internal: true

  - platform: template
    name: "ZE07-CO Carbon Monoxide"
    id: ze07_co_ppm
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co"
    device_class: "aqi"
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 5s
    lambda: |-
      if (!id(ze07_co_raw).has_state()) return NAN;
      float ppm = id(ze07_co_raw).state;
      // ZE07 returns 0-1000ppm directly
      // Apply basic filtering for stability
      return ppm;
    on_value:
      then:
        - component.update: display_component

  # ===== SPS30 PARTICULATE MATTER SENSOR (I2C) =====
  # Measures: PM1.0, PM2.5, PM4, PM10 in µg/m³
  # Based on laser scattering technology
  # Excellent for indoor air quality assessment
  
  - platform: sps30
    i2c_id: bus_a
    pm_1_0:
      name: "SPS30 PM1.0"
      id: sps30_pm1_0
      unit_of_measurement: "µg/m³"
      icon: "mdi:cloud-outline"
      accuracy_decimals: 1
    pm_2_5:
      name: "SPS30 PM2.5"
      id: sps30_pm2_5
      unit_of_measurement: "µg/m³"
      icon: "mdi:cloud"
      accuracy_decimals: 1
      device_class: "pm25"
    pm_4_0:
      name: "SPS30 PM4.0"
      id: sps30_pm4_0
      unit_of_measurement: "µg/m³"
      icon: "mdi:cloud"
      accuracy_decimals: 1
    pm_10_0:
      name: "SPS30 PM10"
      id: sps30_pm10
      unit_of_measurement: "µg/m³"
      icon: "mdi:cloud-alert"
      accuracy_decimals: 1
      device_class: "pm10"
    update_interval: 30s

  # ===== SCD41 CO2 SENSOR (I2C) =====
  - platform: scd4x
    i2c_id: bus_a
    address: 0x62
    update_interval: 5s
    co2:
      name: "SCD41 CO₂"
      id: scd41_co2
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      icon: "mdi:molecule-co2"
      filters:
        - sliding_window_moving_average:
            window_size: 6
            send_every: 1
    temperature:
      name: "SCD41 Temperature (C) Raw"
      id: scd41_temp_c
      accuracy_decimals: 2
      entity_category: diagnostic
      disabled_by_default: true
    humidity:
      name: "SCD41 Humidity"
      id: scd41_hum
      unit_of_measurement: "%"
      accuracy_decimals: 1

  - platform: template
    name: "SCD41 Temperature"
    id: scd41_temp_f
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    update_interval: 5s
    icon: "mdi:thermometer"
    device_class: temperature
    state_class: measurement
    lambda: |-
      if (!id(scd41_temp_c).has_state()) return NAN;
      return id(scd41_temp_c).state * 9.0f/5.0f + 32.0f;

  # ===== BME680 ENVIRONMENTAL + VOC (I2C) =====
  - platform: bme680
    i2c_id: bus_a
    address: 0x77
    update_interval: 5s
    temperature:
      name: "BME680 Temperature"
      id: bme680_temp
      accuracy_decimals: 1
      entity_category: diagnostic
    humidity:
      name: "BME680 Humidity"
      id: bme680_hum
      accuracy_decimals: 1
    pressure:
      name: "BME680 Pressure"
      id: bme680_press
      accuracy_decimals: 1
    gas_resistance:
      name: "BME680 Gas Resistance"
      id: bme680_gas
      entity_category: diagnostic

  - platform: template
    name: "BME680 IAQ Index"
    id: bme680_iaq
    unit_of_measurement: "IAQ"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      // Simplified IAQ calculation from BME680 gas resistance
      if (!id(bme680_gas).has_state()) return NAN;
      
      // BME680 BSEC algorithm output (0-500 scale)
      // 0-50: Excellent, 50-100: Good, 100-200: Acceptable
      // 200-300: Poor, 300-400: Bad, 400-500: Hazardous
      
      float resistance = id(bme680_gas).state;
      float iaq = 0;
      
      // Simplified mapping (actual BSEC would be more complex)
      if (resistance > 50000) iaq = 0;        // Excellent
      else if (resistance > 25000) iaq = 50;  // Good
      else if (resistance > 10000) iaq = 150; // Acceptable
      else if (resistance > 5000) iaq = 250;  // Poor
      else if (resistance > 2000) iaq = 350;  // Bad
      else iaq = 450;                         // Hazardous
      
      return iaq;

  # ===== COMPREHENSIVE AIR QUALITY SCORING =====
  - platform: template
    name: "Air Quality Score V2"
    id: aq_score_v2
    unit_of_measurement: "%"
    icon: "mdi:air-filter"
    device_class: "aqi"
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      float score = 100.0f;
      int sensor_count = 0;
      
      // CO₂ contribution (25%)
      if (id(scd41_co2).has_state()) {
        float co2 = id(scd41_co2).state;
        float co2_penalty = 0.0f;
        if (co2 < 600) co2_penalty = 0;
        else if (co2 < 1000) co2_penalty = (co2 - 600) / 400 * 10;
        else if (co2 < 1500) co2_penalty = 10 + (co2 - 1000) / 500 * 15;
        else if (co2 < 2000) co2_penalty = 25 + (co2 - 1500) / 500 * 15;
        else co2_penalty = 40 + (co2 - 2000) / 2000 * 40;
        score -= co2_penalty * 0.25f;
        sensor_count++;
      }
      
      // PM2.5 contribution (25%)
      if (id(sps30_pm2_5).has_state()) {
        float pm25 = id(sps30_pm2_5).state;
        // WHO guideline: 15µg/m³ 24-hour mean
        float pm25_penalty = 0.0f;
        if (pm25 < 10) pm25_penalty = 0;
        else if (pm25 < 15) pm25_penalty = (pm25 - 10) / 5 * 10;
        else if (pm25 < 25) pm25_penalty = 10 + (pm25 - 15) / 10 * 20;
        else if (pm25 < 35) pm25_penalty = 30 + (pm25 - 25) / 10 * 20;
        else pm25_penalty = 50 + (pm25 - 35) / 35 * 30;
        score -= pm25_penalty * 0.25f;
        sensor_count++;
      }
      
      // CO contribution (25%) - now using ZE07 (more accurate)
      if (id(ze07_co_ppm).has_state()) {
        float co = id(ze07_co_ppm).state;
        float co_penalty = 0.0f;
        if (co < 5) co_penalty = 0;
        else if (co < 35) co_penalty = (co - 5) / 30 * 15;
        else if (co < 100) co_penalty = 15 + (co - 35) / 65 * 25;
        else if (co < 500) co_penalty = 40 + (co - 100) / 400 * 35;
        else co_penalty = 75 + (co - 500) / 500 * 25;
        score -= co_penalty * 0.25f;
        sensor_count++;
      }
      
      // VOC/IAQ contribution (25%)
      if (id(bme680_iaq).has_state()) {
        float iaq = id(bme680_iaq).state;
        float iaq_penalty = 0.0f;
        if (iaq < 50) iaq_penalty = 0;
        else if (iaq < 150) iaq_penalty = (iaq - 50) / 100 * 15;
        else if (iaq < 300) iaq_penalty = 15 + (iaq - 150) / 150 * 20;
        else if (iaq < 400) iaq_penalty = 35 + (iaq - 300) / 100 * 25;
        else iaq_penalty = 60 + (iaq - 400) / 100 * 40;
        score -= iaq_penalty * 0.25f;
        sensor_count++;
      }
      
      if (sensor_count >= 3) {
        if (score < 0) score = 0;
        return score;
      }
      return NAN;
    on_value:
      then:
        - script.execute: evaluate_air_quality_v2

  # ===== AIR QUALITY STATUS TEXT =====
  - platform: template
    name: "AQ Status V2"
    id: aq_status_v2
    icon: "mdi:alert-circle"
    update_interval: 10s
    lambda: |-
      if (!id(aq_score_v2).has_state()) return std::string("NO DATA");
      float score = id(aq_score_v2).state;
      if (score >= 75) return std::string("EXCELLENT");
      else if (score >= 50) return std::string("GOOD");
      else if (score >= 25) return std::string("FAIR");
      else if (score >= 10) return std::string("POOR");
      else return std::string("HAZARDOUS");

  # ===== DATA QUALITY SCORE =====
  - platform: template
    name: "Data Quality V2"
    id: data_quality_v2
    unit_of_measurement: "%"
    icon: "mdi:test-tube"
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      float quality = 100.0f;
      
      if (!id(scd41_co2).has_state()) quality -= 20.0f;
      if (!id(ze07_co_ppm).has_state()) quality -= 20.0f;
      if (!id(sps30_pm2_5).has_state()) quality -= 20.0f;
      if (!id(bme680_iaq).has_state()) quality -= 20.0f;
      
      if (quality < 0) quality = 0;
      return quality;

  # ===== INDIVIDUAL GAS SAFETY STATUS =====
  - platform: template
    name: "CO Safety Status V2"
    id: co_safety_status_v2
    icon: "mdi:alert-circle-outline"
    entity_category: diagnostic
    update_interval: 5s
    lambda: |-
      if (!id(ze07_co_ppm).has_state()) return std::string("NO DATA");
      float ppm = id(ze07_co_ppm).state;
      if (ppm < 5) return std::string("NORMAL");
      else if (ppm < 35) return std::string("ELEVATED");
      else if (ppm < 100) return std::string("WARNING");
      else if (ppm < 500) return std::string("ALERT");
      else return std::string("CRITICAL");

  - platform: template
    name: "PM2.5 Safety Status"
    id: pm25_safety_status
    icon: "mdi:alert-circle-outline"
    entity_category: diagnostic
    update_interval: 10s
    lambda: |-
      if (!id(sps30_pm2_5).has_state()) return std::string("NO DATA");
      float pm = id(sps30_pm2_5).state;
      if (pm < 10) return std::string("EXCELLENT");
      else if (pm < 15) return std::string("GOOD");
      else if (pm < 25) return std::string("ACCEPTABLE");
      else if (pm < 35) return std::string("POOR");
      else return std::string("HAZARDOUS");

  - platform: template
    name: "CO₂ Safety Status V2"
    id: co2_safety_status_v2
    icon: "mdi:alert-circle-outline"
    entity_category: diagnostic
    update_interval: 5s
    lambda: |-
      if (!id(scd41_co2).has_state()) return std::string("NO DATA");
      float ppm = id(scd41_co2).state;
      if (ppm < 600) return std::string("EXCELLENT");
      else if (ppm < 1000) return std::string("GOOD");
      else if (ppm < 1500) return std::string("ACCEPTABLE");
      else if (ppm < 2000) return std::string("POOR");
      else return std::string("CRITICAL");

binary_sensor:
  # ===== CRITICAL ALERT TRIGGERS =====
  - platform: template
    name: "CO Alert (>100ppm)"
    id: co_alert_v2
    icon: "mdi:fire-alert"
    device_class: safety
    update_interval: 5s
    lambda: |-
      if (!id(ze07_co_ppm).has_state()) return false;
      return id(ze07_co_ppm).state > 100.0f;

  - platform: template
    name: "PM2.5 Alert (>35µg/m³)"
    id: pm25_alert
    icon: "mdi:fire-alert"
    device_class: safety
    update_interval: 10s
    lambda: |-
      if (!id(sps30_pm2_5).has_state()) return false;
      return id(sps30_pm2_5).state > 35.0f;

  - platform: template
    name: "CO₂ Alert (>2000ppm)"
    id: co2_alert_v2
    icon: "mdi:fire-alert"
    device_class: safety
    update_interval: 5s
    lambda: |-
      if (!id(scd41_co2).has_state()) return false;
      return id(scd41_co2).state > 2000.0f;

  - platform: template
    name: "Hazardous AQ V2"
    id: hazardous_aq_v2
    icon: "mdi:fire-alert"
    device_class: safety
    update_interval: 10s
    lambda: |-
      if (!id(aq_score_v2).has_state()) return false;
      return id(aq_score_v2).state < 10.0f;

script:
  # ===== AIR QUALITY ALERT EVALUATION =====
  - id: evaluate_air_quality_v2
    then:
      - logger.log:
          format: "V2 AQ Score: %.1f%%, Status: %s"
          args: [id(aq_score_v2).state, "Evaluated"]
      
      # Determine alert level
      - if:
          condition:
            lambda: |-
              if (!id(aq_score_v2).has_state()) return false;
              return id(aq_score_v2).state < 10.0f;
          then:
            - globals.set:
                id: aq_alert_level
                value: "3"
      - if:
          condition:
            lambda: |-
              if (!id(aq_score_v2).has_state()) return false;
              return id(aq_score_v2).state >= 10.0f && id(aq_score_v2).state < 25.0f;
          then:
            - globals.set:
                id: aq_alert_level
                value: "2"
      - if:
          condition:
            lambda: |-
              if (!id(aq_score_v2).has_state()) return false;
              return id(aq_score_v2).state >= 25.0f && id(aq_score_v2).state < 50.0f;
          then:
            - globals.set:
                id: aq_alert_level
                value: "1"
      - if:
          condition:
            lambda: |-
              if (!id(aq_score_v2).has_state()) return false;
              return id(aq_score_v2).state >= 50.0f;
          then:
            - globals.set:
                id: aq_alert_level
                value: "0"

button:
  # ===== CALIBRATION & MAINTENANCE =====
  - platform: template
    name: "Force SCD41 Recalibration"
    id: btn_force_scd41_calib
    icon: "mdi:restart"
    entity_category: config
    on_press:
      then:
        - logger.log:
            level: WARN
            format: "Forcing SCD41 recalibration"
        - globals.set:
            id: g_baseline_valid
            value: "true"
        - globals.set:
            id: g_calibration_count
            value: !lambda 'return id(g_calibration_count) + 1;'
        - globals.set:
            id: g_calibration_timestamp
            value: !lambda 'return millis() / 1000;'

  - platform: template
    name: "Reset System"
    id: btn_reset_system_v2
    icon: "mdi:restart-alert"
    entity_category: config
    on_press:
      then:
        - logger.log:
            level: WARN
            format: "System reset requested"
        - globals.set:
            id: aq_alert_level
            value: "0"
        - globals.set:
            id: g_baseline_valid
            value: "false"
